blank_issues_enabled: false
contact_links:
  - name: General question / discussion
    url: https://github.com/nyas1/Material-You-app-list/discussions
    about: Please use discussions for non-app-add topics.
